[tasks.fmt]
args = ["fmt"]
command = "cargo"
toolchain = "nightly"

[tasks.check]
args = ["check", "--all-features"]
command = "cargo"

[tasks.clippy]
args = ["clippy"]
command = "cargo"

[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.run]
args = ["run"]
command = "cargo"
dependencies = ["checkfc"]

[tasks.docker-build]
args = ["build", "-t", "fuwn/september:latest", "."]
command = "docker"
dependencies = ["checkfc"]

