name: Check ✅
on:
  workflow_dispatch:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: Check ✅
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4
      - name: Toolchain 🧰
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Clippy 📎
        run: cargo clippy --all-features --verbose
