name: Check ✅
on:
  workflow_dispatch:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: Check ✅
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4
      - name: Toolchain 🧰
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Tests 🧪
        run: cargo test --locked --all-features
      - name: Clippy 📎
        run: cargo clippy --locked --all-targets --all-features -- -D warnings
      - name: Nightly rustfmt 🧰
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Formatting 🎨
        run: cargo +nightly fmt --all -- --check
